{% set name = "napari-morphodynamics" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-morphodynamics-{{ version }}.tar.gz
  sha256: f4c5793ed3ce2403e093c8f808ea5d4b2399e3620cc85b278c38b0492b1bf089

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.9
    - setuptools
    - setuptools-scm
    - wheel
  run:
    - morphodynamics
    - napari-convpaint
    - napari-guitils
    - napari-matplotlib
    - python >=3.9

test:
  imports:
    - napari_morphodynamics
  commands:
    - pip list
    # - pip check  # Fails due to aicsimageio
  requires:
    - pip
    - pyqt

about:
  home: https://pypi.org/project/napari-morphodynamics
  summary: Interface to run the morphodynamics package.
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/guiwitz/napari-morphodynamics

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
